apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # Base64 encoded values
  # root password: rootpass
  mysql-root-password: cm9vdHBhc3M=
  # database name: userdb
  mysql-database: dXNlcmRi
  # username: timi
  mysql-user: dGltaQ==
  # user password: rootpass
  mysql-password: cm9vdHBhc3M=